jdk_basedir:          /usr/lib/java   # JDK Install dir
jdk_version:          jdk1.8.0_131

jboss_home:           /opt            # JBoss install dir
http_port:            8090            # JBoss port for http connections
https_port:           8443            # JBoss port for https connections

wildfly_home:         /opt
wildfly_version:      10.1.0.Final
wildfly_user:         wildfly

oracle_http_port:     8091            # Oracle port for http connections
oracle_listener_port: 1521            # Oracle listener port
oracle_password:      adminpasswd     # Admin, sys and system users passwords

dev_tools_dir:        /usr/lib
maven_version:        3.5.0
gradle_version:       4.2

ldap_username:        admin
ldap_password:        secret
ldap_basedn:          dc=golili,dc=net
ldap_users:
  admin:
    cn: System Administrator
    givenname: System
    sn: Administrator
    mail: admin@golili.net
    userpassword: admin
  lnovo:
    cn: Luis Novo
    givenname: Luis
    sn: Novo
    mail: lnovo@golili.net
    userpassword: alibaba
  erodrigyez:
    cn: Elena Rodriguez
    givenname: Elena
    sn: Rodriguez
    mail: erodriguez@golili.net
    userpassword: alibaba
  aperez:
    cn: Alberto Perez
    givenname: Alberto
    sn: Perez
    mail: aperez@golili.net
    userpassword: alibaba

ldap_groups:
  - name: administrators
    members:
      - admin
  - name: developers
    members:
      - lnovo
      - erodriguez
      - aperez


nexus_version:        3.6.0-02
nexus_user:           nexus           # Nexus OS user
nexus_home:           /opt/nexus
nexus_port:           8081
nexus_repo_user:      admin           # Nexus app user
nexus_repo_password:  admin123        # Nexus app password

go_server_port:     8153        # go.cd http port
go_server_ssl:      8154        # go.cd ssl listen port for agents
go_pipelines_group: golil.net   # go.cd pipelines group name
go_environment:     Integration # go.cd initial configured environment

jenkins_user:         jenkins
jenkins_port:         8080
jenkins_home:         /var/lib/jenkins
jenkins_admin_email:  jenkins@golili.net
jenkins_params:
  url_username: admin
  url_password: admin
  url: 'http://localhost: 8080'
jenkins_plugins:
  - blueocean
 # - build-timeout
 # - credentials
 # - durable-task
  - email-ext
 # - external-monitor-job
  - git
  - gradle
 # - handlebars
 # - jquery-detached
  - ldap
 # - mapdb-api
 # - matrix-auth
 # - momentjs
 # - nexus-jenkins-plugin
 # - pam-auth
 # - pipeline-github-lib
 # - pipeline-model-extensions
 # - pipeline-rest-api
 # - pipeline-stage-view
 # - resource-disposer
 # - ssh-slaves
 # - subversion
 # - timestamper
 # - workflow-aggregator
 # - workflow-api
 # - workflow-basic-steps
 # - workflow-cps
 # - workflow-cps-global-lib
 # - workflow-durable-task-step
 # - workflow-job
 # - workflow-multibranch
 # - workflow-scm-step
 # - workflow-step-api
 # - workflow-support
 # - ws-cleanup
