- src: capitanh.openldap-ansible-role
- src: capitanh.oraclejdk-ansible-role
#- src: capitanh.mysql-ansible-role
#- src: capitanh.jenkins-ansible-role
#- src: capitanh.jboss-ansible-role
#- src: capitanh.oraclexe-ansible-role
#- src: capitanh.nexus-ansible-role
- src: capitanh.gocd-ansible-role
