---
provisioning:   ansible  # [puppet|ansible]
vb_name:        devserver
vb_memory:      4096
vb_cpus:        2
#box_name:      ubuntu/trusty64
box_name:       bento/centos-7.2
host_name:      devserver.golili.net
locale_lc_all:  en_US.UTF-8
locale_lang:    en_US.UTF-8
roles_path:     ~/.ansible/roles
ports:
- guestPort:  8080
  hostPort:   8080
- guestPort:  8081
  hostPort:   8081
- guestPort:  1521
  hostPort:   1521
- guestPort:  389
  hostPort:   10389
- guestPort:  8153
  hostPort:   8153
- guestPort:  9990
  hostPort:   9990
